NCD-769: Update UI on VoltageConfiguration component
NordicSemiconductor/pc-nrfconnect-board-configurator pull request #81
Opened 2024-03-12 07:58 UTC by cybic

* Move preset buttons
 * Resize buttons
 * Move description
 * Add some air

![image](https://github.com/NordicSemiconductor/pc-nrfconnect-board-configurator/assets/980843/07743a83-a8ff-4f6a-81b6-04b0723b8f29)

![image](https://github.com/NordicSemiconductor/pc-nrfconnect-board-configurator/assets/980843/865750e3-e641-435d-b47b-7a41dd323f58)

2024-03-12 09:01 UTC, greg-fer requested changes
@cybic , how come the screenshot is from v0.1.10, if you already released v0.1.11?

2024-03-12 14:31 UTC, cybic commented
> @cybic , how come the screenshot is from v0.1.10, if you already released v0.1.11? Shouldn't it be from v0.1.12?

You're right! I forgot to restart the app. The title is only updated when the Board Configurator is restarted from the launcher. Good catch. :+1:

2024-03-13 08:08 UTC, greg-fer approved these changes

2024-03-13 08:12 UTC, greg-fer commented
https://github.com/NordicSemiconductor/pc-nrfconnect-board-configurator/pull/80

2024-03-15 09:18 UTC, merged